language: ruby
rvm: 2.7.1
cache: bundler
sudo: required
services:
  - mysql
env:
  - DB=mysql
  - RAILS_ENV=test
script:
  - bundle install
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec bundler-audit check --update
  - bundle exec rubocop
  - bundle exec rspec
before_script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create
