version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/rails/Dockerfile
    env_file: docker/rails/env
    command: bash -c "rm ./tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/opt/webapp
      - log-data:/webapp/log
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    restart:
      always
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - db-data:/var/lib/mysql
    ports:
      - 43306:3306

volumes:
  log-data:
  db-data:

